---
  - name: openshift-vanilla
    type: ocp
    location: agents/openshift-vanilla
    outputs:
      hosts: agents/openshift-vanilla/outputs/localhost/etc/hosts
    topic: OCP-4.4
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok

  - name: rh-cnf
    type: cnf
    location: agents/rh-cnf
    inputs:
      hosts: agents/rh-cnf/hosts
    topic: RH-CNF-0.1
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok
