---
  - name: openshift-vanilla
    type: ocp
    location: /home/yassine/dci/dci-pipeline/dcipipeline/agents/openshift-vanilla
    outputs:
      - ocp_config: /home/yassine/dci/dci-pipeline/dcipipeline/agents/openshift-vanilla/config.json
    topic: OCP-4.4
    fallback_last_succeed: true

  - name: rh-cnf
    type: cnf
    location: /home/yassine/dci/dci-pipeline/dcipipeline/agents/rh-cnf
    inputs:
      - ocp_config: /home/yassine/dci/dci-pipeline/dcipipeline/agents/openshift-vanilla/config.json
    topic: RH-CNF
